function tracks=fuseMeasurements(meas,prior,t,c)
% Nearest-neighbor measurement fusion and alpha-beta tracking. Track IDs
% are generated by perception, never copied from actor truth IDs.
if isempty(prior)
    tracks=repmat(struct('id',0,'type','unknown','x',0,'y',0,'vx',0, ...
        'vy',0,'radius',1.1,'length',2.5,'width',1.2, ...
        'confidence',0.5,'cov',eye(2),'lastSeen',0),0,1);
else
    tracks=prior;
end
if isempty(prior), nextID=1; else, nextID=max([prior.id])+1; end
for k=1:numel(tracks)
    dt=max(0,t-tracks(k).lastSeen);
    tracks(k).x=tracks(k).x+tracks(k).vx*min(dt,c.dt);
    tracks(k).y=tracks(k).y+tracks(k).vy*min(dt,c.dt);
    tracks(k).cov=tracks(k).cov+0.05*eye(2);
end
for j=1:numel(meas)
    z=[meas(j).x meas(j).y];
    if any(~isfinite(z)), continue; end
    if isempty(tracks), idx=[];
    else
        dist=arrayfun(@(a)hypot(a.x-z(1),a.y-z(2)),tracks);
        [d,idx]=min(dist);
        if d>3, idx=[]; end
    end
    if isempty(idx)
        initialConfidence=0.35;
        if strcmp(meas(j).source,'camera'), initialConfidence=0.75; end
        tr=struct('id',nextID,'type',meas(j).type,'x',z(1),'y',z(2), ...
            'vx',0,'vy',0,'radius',1.1,'length',2.5,'width',1.2, ...
            'confidence',initialConfidence,'cov',eye(2),'lastSeen',t);
        nextID=nextID+1; tracks(end+1)=tr; %#ok<AGROW>
    else
        dt=max(c.dt,t-tracks(idx).lastSeen);
        residual=z-[tracks(idx).x tracks(idx).y];
        tracks(idx).x=tracks(idx).x+0.6*residual(1);
        tracks(idx).y=tracks(idx).y+0.6*residual(2);
        tracks(idx).vx=max(-8,min(8,tracks(idx).vx+0.12*residual(1)/dt));
        tracks(idx).vy=max(-8,min(8,tracks(idx).vy+0.12*residual(2)/dt));
        tracks(idx).confidence=min(1,tracks(idx).confidence+0.08);
        tracks(idx).cov=max(0.1,0.7*tracks(idx).cov(1,1))*eye(2);
        tracks(idx).lastSeen=t;
    end
end
tracks=tracks(arrayfun(@(a)t-a.lastSeen<=c.trackCoast,tracks));
end
