function m=metrics(log,sc,outcome,collision,emergencies)
dt=mean(diff(log.time)); if isnan(dt), dt=0; end
replans=log.latencyMs(log.latencyMs>0);
if isempty(replans), replans=nan; end
sortedLatency=sort(replans);
p95=sortedLatency(max(1,ceil(0.95*numel(sortedLatency))));
dxy=diff(log.ego(:,1:2));
steer=log.control(:,1); acc=log.control(:,2);
v=log.ego(:,4); yaw=log.ego(:,3);
curvature=tan(steer)/2.7;
ttc=log.ttc(isfinite(log.ttc));
if isempty(ttc), minTTC=nan; else, minTTC=min(ttc); end
clearance=log.clearance(isfinite(log.clearance));
if isempty(clearance), minClear=nan; else, minClear=min(clearance); end
jerk=diff(acc)/max(dt,eps);
m=struct('scenario',sc.id,'name',sc.name,'success',strcmp(outcome,'goal'), ...
    'outcome',outcome,'collisionCount',collision,'duration',log.time(end), ...
    'pathLength',sum(hypot(dxy(:,1),dxy(:,2))), ...
    'averageSpeed',mean(v),'minimumClearance',minClear,'minimumTTC',minTTC, ...
    'meanReplanMs',mean(replans),'p95ReplanMs',p95, ...
    'maxLongAccel',max(abs(acc)),'maxLateralAccel',max(abs(v.^2.*curvature)), ...
    'rmsJerk',sqrt(mean(jerk.^2)),'curvatureChange',sum(abs(diff(curvature))), ...
    'emergencyInterventions',emergencies,'replans',numel(replans), ...
    'finalX',log.ego(end,1),'finalY',log.ego(end,2), ...
    'headingChange',sum(abs(diff(yaw))));
end
