function r=vdbMetrics(egoSeries,decisionSeries,scenarioId,sc)
% Score the actual Vehicle Dynamics Blockset plant, not the 2D baseline.
c=sih.config('fast','synthetic_fusion');
if nargin<4, sc=sih.makeScenario(scenarioId,c); end
t=egoSeries.Time(:); raw=egoSeries.Data;
assert(size(raw,2)==5 && numel(t)==size(raw,1));
ego=[raw(:,1),raw(:,2),-raw(:,3),raw(:,4)];
dt=decisionSeries.Time(:); decisions=decisionSeries.Data;
assert(size(decisions,2)>=30 && numel(dt)==size(decisions,1));
clearance=inf(numel(t),1); collision=false(numel(t),1);
roadDeparture=false(numel(t),1);
for i=1:numel(t)
    actors=sih.actorStates(sc,t(i));
    for k=1:numel(actors)
        gap=hypot(ego(i,1)-actors(k).x,ego(i,2)-actors(k).y) ...
            -(c.egoWidth/2+actors(k).radius);
        clearance(i)=min(clearance(i),gap);
        collision(i)=collision(i) || gap<0;
    end
    roadDeparture(i)=abs(ego(i,2))>sc.roadHalfWidth-c.egoWidth/2;
end
goal=find(ego(:,1)>=sc.goalX-1 & abs(ego(:,4))<1.5,1);
if isempty(goal), finish=numel(t); outcome='timeout';
else, finish=goal; outcome='goal'; end
if any(collision(1:finish)), outcome='collision'; end
if any(roadDeparture(1:finish)), outcome='road_departure'; end
keepD=dt<=t(finish)+1e-8;
decisions=decisions(keepD,:); dt=dt(keepD);
latencies=decisions(decisions(:,7)>0,7);
if isempty(latencies), latencies=nan; end
ttc=decisions(:,6); ttc=ttc(ttc<99);
if isempty(ttc), minimumTTC=nan; else, minimumTTC=min(ttc); end
longAccel=sum(decisions(:,2:3),2)/2000;
jerk=diff(longAccel)./max(diff(dt),eps);
if isempty(jerk), jerk=nan; end
brake=longAccel<=-c.emergencyDecel+0.01;
episodes=sum(diff([false;brake])==1);
sorted=sort(latencies);
metrics=struct('scenario',scenarioId,'success',strcmp(outcome,'goal'), ...
    'outcome',outcome,'collisionCount',sum(diff([false;collision(1:finish)])==1), ...
    'duration',t(finish),'minimumClearance',min(clearance(1:finish)), ...
    'minimumTTC',minimumTTC,'meanReplanMs',mean(latencies), ...
    'p95ReplanMs',sorted(max(1,ceil(0.95*numel(sorted)))), ...
    'pathLength',sum(hypot(diff(ego(1:finish,1)), ...
        diff(ego(1:finish,2)))), ...
    'maxLongAccel',max(abs(longAccel)), ...
    'rmsJerk',sqrt(mean(jerk.^2)), ...
    'emergencyInterventions',episodes, ...
    'finalX',ego(finish,1),'finalY',ego(finish,2), ...
    'finalSpeed',ego(finish,4), ...
    'cameraMax',max(decisions(:,27)), ...
    'radarMax',max(decisions(:,28)), ...
    'lidarMax',max(decisions(:,29)));
r=struct('id',scenarioId,'name',sc.name,'metrics',metrics, ...
    'time',t(1:finish),'ego',ego(1:finish,:), ...
    'clearance',clearance(1:finish), ...
    'decisionTime',dt,'decisions',decisions, ...
    'roadHalfWidth',sc.roadHalfWidth,'goalX',sc.goalX, ...
    'backend','Vehicle Dynamics Blockset 3DOF Single Track');
end
