function modelPath=build_simulink_model
setup_project;
root=fileparts(mfilename('fullpath'));
modelDir=fullfile(root,'models'); if ~exist(modelDir,'dir'), mkdir(modelDir); end
name='SIH_AutonomousDriving'; modelPath=fullfile(modelDir,[name '.slx']);
if bdIsLoaded(name), close_system(name,0); end
new_system(name);
set_param(name,'Solver','FixedStepDiscrete','FixedStep','0.1', ...
    'StopTime','25','SimulationMode','normal');
add_block('simulink/Sources/Clock',[name '/Simulation time'], ...
    'Position',[40 95 70 125]);
add_block('simulink/Ports & Subsystems/Subsystem',[name '/Closed-loop autonomy'], ...
    'Position',[150 60 380 160]);
sub=[name '/Closed-loop autonomy'];
delete_line(sub,'In1/1','Out1/1');
delete_block([sub '/In1']); delete_block([sub '/Out1']);
add_block('simulink/Ports & Subsystems/In1',[sub '/Time'], ...
    'Position',[30 65 60 85]);
add_block('simulink/User-Defined Functions/Interpreted MATLAB Function', ...
    [sub '/Environment Sensors Perception Prediction Risk Behavior Planning Control Dynamics'], ...
    'MATLABFcn','sih.simulinkPipeline(u)', ...
    'OutputDimensions','10','SampleTime','0.1', ...
    'Position',[100 52 480 100]);
add_block('simulink/Ports & Subsystems/Out1',[sub '/State and diagnostics'], ...
    'Position',[530 65 560 85]);
add_line(sub,'Time/1', ...
    'Environment Sensors Perception Prediction Risk Behavior Planning Control Dynamics/1');
add_line(sub, ...
    'Environment Sensors Perception Prediction Risk Behavior Planning Control Dynamics/1', ...
    'State and diagnostics/1');
add_block('simulink/Sinks/To Workspace',[name '/Metrics and logging'], ...
    'VariableName','egoLog','SaveFormat','Timeseries', ...
    'Position',[470 93 620 127]);
add_line(name,'Simulation time/1','Closed-loop autonomy/1');
add_line(name,'Closed-loop autonomy/1','Metrics and logging/1');
save_system(name,modelPath); close_system(name,0);
end
